openapi: 3.0.0

info:
    version: 1.0.0
    title: baldeweg Desk
    description: baldeweg Desk contains services like letter and wiki.

externalDocs:
    description: Find out more about baldeweg Desk
    url: https://github.com/abaldeweg/

servers:
    - url: http://localhost:8000/api

tags:
    - name: user
      description: User
    - name: letter
      description: Letter

paths:
    # User
    /me:
        get:
            tags:
                - user
            description: Shows the current User
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/UserResponse"
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"

    /password:
        put:
            tags:
                - user
            description: Updates the password
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - password
                            properties:
                                password:
                                    type: string
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/UserResponse"
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"

    /login_check:
        post:
            tags:
                - user
            description: Authenticates the user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - username
                                - password
                            properties:
                                username:
                                    type: string
                                password:
                                    type: string
            responses:
                "200":
                    description: Returns a new token
                    content:
                        application/json:
                            schema:
                                type: object
                                required:
                                    - token
                                    - refresh_token
                                properties:
                                    token:
                                        type: string
                                    refresh_token:
                                        type: string
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"

    /token/refresh:
        post:
            tags:
                - user
            description: Returns a new token
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - refresh_token
                            properties:
                                refresh_token:
                                    type: string
            responses:
                "200":
                    description: Returns the token
                    content:
                        application/json:
                            schema:
                                type: object
                                required:
                                    - token
                                    - refresh_token
                                properties:
                                    token:
                                        type: string
                                    refresh_token:
                                        type: string
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"

    # letter
    /letter/:
        get:
            tags:
                - letter
            description: Returns a list of letters
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/LetterResponse"
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
    /letter/new:
        post:
            tags:
                - letter
            description: Creates a new item
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/LetterRequest"
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/LetterResponse"
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
    /letter/{letter}/download:
        get:
            tags:
                - letter
            parameters:
                - name: letter
                  in: path
                  required: true
                  description: Id of the letter
                  schema:
                      type: string
            description: Returns a letter
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                type: string
                                format: binary
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
    /letter/{letter}:
        get:
            tags:
                - letter
            parameters:
                - name: letter
                  in: path
                  required: true
                  description: Id of the letter
                  schema:
                      type: string
            description: Returns a letter
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/LetterResponse"
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
        put:
            tags:
                - letter
            parameters:
                - name: letter
                  in: path
                  required: true
                  description: id of the letter
                  schema:
                      type: string
            description: Updates a letter
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/LetterRequest"
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/LetterResponse"
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
        delete:
            tags:
                - letter
            parameters:
                - name: letter
                  in: path
                  required: true
                  description: id of the letter
                  schema:
                      type: string
            description: Deletes a letter
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/LetterResponse"
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT

    schemas:
        ErrorResponse:
            type: object
            required:
                - code
                - message
            properties:
                code:
                    type: integer
                message:
                    type: string

        UserResponse:
            type: object
            required:
                - id
                - username
                - roles
                - branch
                - isUser
                - isAdmin
            properties:
                id:
                    type: integer
                username:
                    type: string
                roles:
                    type: array
                    items:
                        type: string
                branch:
                    type: object
                    properties:
                        id:
                            type: string
                        name:
                            type: string
                        steps:
                            type: string
                        currency:
                            type: string
                        ordering:
                            type: string
                isUser:
                    type: boolean
                isAdmin:
                    type: boolean

        LetterRequest:
            type: object
            required:
                - title
                - meta
                - content
            properties:
                title:
                    type: string
                meta:
                    type: string
                content:
                    type: string

        LetterResponse:
            type: object
            required:
                - id
                - title
                - meta
                - content
            properties:
                id:
                    type: string
                title:
                    type: string
                meta:
                    type: string
                content:
                    type: string

security:
    - bearerAuth: []
